# Generated by Django 5.2.4 on 2025-07-19 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_birth_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="connections",
            new_name="relations",
        ),
    ]
