# Generated by Django 5.2.4 on 2025-07-18 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("socials", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="annotation",
            old_name="noteId",
            new_name="note_id",
        ),
    ]
