# Generated by Django 5.2.4 on 2025-07-19 04:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socials", "0003_post_delete_annotation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="mentions",
            field=models.ManyToManyField(
                blank=True, related_name="mentioned_in", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
